export const GETINDEXFOOD = 'GETINDEXFOOD'

export const GETXICAN = 'GETXICAN'
export const GETTIANDIAN = 'GETTIANDIAN'
export const GETFASHI = 'GETFASHI'

export const CHANGELOADING = 'CHANGELOADING'

export const GETCHINAFOOD = 'GETCHINAFOOD'
export const CHANGECURRENTPAGE = 'CHANGECURRENTPAGE'

export const CHANGECARTDATA = 'CHANGECARTDATA'

export const CHANGECARTDATAFROMCARTPAGE = 'CHANGECARTDATAFROMCARTPAGE'
export const DELETECARTITEM = 'DELETECARTITEM'
